import type { Building, Recipe, RecipeInput, RecipeOutput } from '@/shared/@types/building.type'

/** An invalid plan has no trustworthy production totals or graph. */
export interface ProductionPlanIssue {
  code: 'cycle' | 'missing-recipe' | 'invalid-rate'
  itemId: string
  message: string
  path?: readonly string[]
}

/** One physical coproduct rate assigned once to a specific consuming recipe. */
export interface ByproductAllocation {
  sourceItemId: string
  consumerItemId: string
  itemId: string
  amountPerMinute: number
}

export interface RawInputDemand {
  itemId: string
  amountPerMinute: number
}

export interface ProductionStep {
  itemId: string
  buildingId: string
  buildingName: string
  /** Net items/min for self-recycling recipes; otherwise the regular recipe output rate. */
  recipeOutputIpm: number
  targetIpm: number
  buildingLoad: number
  buildingCount: number
  /** Source power per machine in MW; undefined means unknown. */
  buildingPower?: number
  supplyCount: number
  /** Self-input is handled internally and excluded from external dependencies. */
  inputs: readonly RecipeInput[]
  recipeId?: string
  /** Rate that circulates inside this recipe, not additional external demand. */
  recycledIpm?: number
  /** Source-confirmed byproducts generated by the configured load; allocation is tracked separately. */
  extraOutputs?: readonly RecipeOutput[]
}

export interface ProductionPlan {
  targetId: string
  targetIpm: number
  isRawTarget: boolean
  supplyCountByItem: Record<string, number>
  supplyCountInventory: Record<string, number>
  steps: ProductionStep[]
  /** Remaining external item demand after configured supply is applied. */
  rawInputs: readonly RawInputDemand[]
  stats: { buildings: number; power: number | null }
  issues: readonly ProductionPlanIssue[]
  /** Actual assigned coproduct flows, excluding unused generated quantities. */
  byproductAllocations?: readonly ByproductAllocation[]
}

export interface BuildProductionPlanParams {
  buildings: readonly Building[]
  producerBuildingsByItemId: ReadonlyMap<string, readonly Building[]>
  targetId: string
  targetIpm: number
  isRawTarget: boolean
  /** Authoritative raw item IDs distinguish external minerals from broken recipe references. */
  rawItemIds?: ReadonlySet<string>
  /** Catalog-backed items acquired outside machines, distinct from raw minerals and coproducts. */
  externalItemIds?: ReadonlySet<string>
  supplyCountByItem: Record<string, number>
  /** An explicit per-product recipe ID, independent from machine and file ordering. */
  recipeIdByItemId?: Record<string, string>
}

export interface PlanResolver {
  buildings: readonly Building[]
  getBuildingForItem: (itemId: string) => Building | null
  getRecipeForItem: (itemId: string) => Recipe | null
}
